changelog:
  labels:
    unreleased: "unreleased"
    important_notes: "Important notes"
    types:
      added: "Added"
      changed: "Changed"
      deprecated: "Deprecated"
      removed: "Removed"
      fixed: "Fixed"
      security: "Security"
      other: "Other"
      number_of_changes:
        singular: "change"
        plural: "changes"
    configuration:
      heading: "Configuration changes"
      type: "Type"
      actions:
        add: "Added"
        update: "Updated"
        delete: "Deleted"
      with_default_value: "with default value"
      description: "Description"