name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test files
        run: ls -l && ls -l ./changelog && echo "v${GITHUB_REF/refs\/tags\//} && ls -l ./changelog/v${GITHUB_REF/refs\/tags\//}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          #  when tag has 'v' in name no need of adding it before ${GITHUB_REF/refs\/tags\//
          body_path: ./changelog/v${GITHUB_REF/refs\/tags\//}/version-summary.md
        env:
          # Cannot use GITHUB_TOKEN because of:
          # https://github.com/orgs/community/discussions/27028
          GITHUB_TOKEN: ${{ secrets.LOGCHANGE_PAT_TOKEN }}