name: Prepare version for next release and create tag

on:
  push:
    branches: [ release ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      #       mvn install is used to install this project as a
      #       plugin and the use it as plugin to create changelog
      - name: Release and Generate CHANGELOG
        run: mvn install && mvn dev.logchange:logchange-maven-plugin:release --non-recursive

      - name: Set up Git
        run: git config --global user.name logchange-bot &&  git config --global user.email logchange-bot@logchange.dev

      - name: Commit generated CHANGELOG
        run: git status && git add ./changelog/ &&  git commit -am "Generated CHANGELOG.md and prepare version for next release" || echo "Nothing to commit"

      - name: Push generated CHANGELOG
        run: git push origin release

      # Worth reading regarding GITHUB TOKEN
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      - name: Java Maven release
        uses: qcastel/github-actions-maven-release@v1.12.34
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          release-branch-name: "release"
          version-minor: true
          skip-perform: true
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "release to main - preparation for next development cycle"
          pr_body: "Autogenerated PR"
          pr_allow_empty: true
          pr_assignee: "marwin1991"
