name: Renovate
on:
  - schedule:
      - cron: '0 7 * * *'
  - workflow_dispatch
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.11
        with:
          token: ${{ secrets.LOGCHANGE_PAT_TOKEN }}
          configurationFile: .github/renovate-config.js
        env:
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: ".*"
          LOG_LEVEL: debug


