name: Renovate
on:
  schedule:
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@latest
        with:
          token: ${{ secrets.LOGCHANGE_PAT_TOKEN }}
          onboarding: false,
          requireConfig: false