name: Renovate
on:
  schedule:
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.20.0
        with:
          token: ${{ secrets.LOGCHANGE_PAT_TOKEN }}
          configurationFile: .github/renovate-config.js
